export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const USER_LIST = "USER_LIST";

export const OPEN_SIDER = "OPEN_SIDER";
export const CLOSE_SIDER = "CLOSE_SIDER";

export const FRIEND_NOT_SELECTED = "FRIEND_NOT_SELECTED";
export const FRIEND_SELECTED = "FRIEND_SELECTED";
export const DELETE_FRIEND = "DELETE_FRIEND";

export const MESSAGE_NOT_SELECTED = "MESSAGE_NOT_SELECTED";
export const MESSAGE_SELECTED = "MESSAGE_SELECTED";

export const UPDATE_USER_STATUS = "UPDATE_USER_STATUS";

export const UPDATE_CHATS = "UPDATE_CHATS";
export const CHAT_INIT = "CHAT_INIT";
export const SET_URL_IN_MESSAGE = "SET_URL_IN_MESSAGE";
export const BULK_CHAT_INIT = "BULK_CHAT_INIT";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
